name: jumplink.vouchers::lang.vouchers.label
form: $/jumplink/vouchers/models/voucher/fields.yaml
modelClass: JumpLink\Vouchers\Models\Voucher
defaultRedirect: jumplink/vouchers/vouchers

create:
    title: jumplink.vouchers::lang.vouchers.create_title
    redirect: jumplink/vouchers/vouchers/update/:id
    redirectClose: jumplink/vouchers/vouchers

update:
    title: jumplink.vouchers::lang.vouchers.label
    redirect: jumplink/vouchers/vouchers
    redirectClose: jumplink/vouchers/vouchers
