name: jumplink.vouchers::lang.redemptions.label
form: $/jumplink/vouchers/models/redemption/fields.yaml
modelClass: JumpLink\Vouchers\Models\Redemption
defaultRedirect: jumplink/vouchers/redemptions

update:
    title: jumplink.vouchers::lang.redemptions.label
    redirect: jumplink/vouchers/redemptions
    redirectClose: jumplink/vouchers/redemptions
