title: jumplink.vouchers::lang.orders.menu_label
list: $/jumplink/vouchers/models/voucherorder/columns.yaml
modelClass: JumpLink\Vouchers\Models\VoucherOrder
recordUrl: jumplink/vouchers/orders/update/:id
noRecordsMessage: backend::lang.list.no_records
showSetup: true
recordsPerPage: 50
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
        mode: all
