name: jumplink.vouchers::lang.orders.label
form: $/jumplink/vouchers/models/voucherorder/fields.yaml
modelClass: JumpLink\Vouchers\Models\VoucherOrder
defaultRedirect: jumplink/vouchers/orders

update:
    title: jumplink.vouchers::lang.orders.label
    redirect: jumplink/vouchers/orders
    redirectClose: jumplink/vouchers/orders
